# Salesforce Ant deployment properties
# Note: sf.password should be your password + security token

sf.username=bhavaniyannam443229@agentforce.com
sf.password=Bhavani@12w2aZJpQlf8um1FgxsZWBi0mK
sf.serverurl=https://login.salesforce.com

# For sandbox, use:
# sf.serverurl=https://test.salesforce.com
